ausgHomepage:
  component: "./node_modules/@sls-next/serverless-component"
  inputs:
    domain: ["www", "ausg.me"]
    domainType: "both"
    certificate:
      cloudFrontDefaultCertificate: false
      acmCertificateArn: "arn:aws:acm:us-east-1:978567334665:certificate/212b55f9-3dd0-4ecd-a3f7-6e134ccdfaa9"
