name: Continuous Deployment

on:
  push:
    branches:
      - "dev"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Package Setup
        run: yarn
        working-directory: ./client

      - name: Test
        run: yarn test
        working-directory: ./client

      - name: Analyze
        run: yarn analyze
        working-directory: ./client

      - name: Deploy
        run: yarn deploy
        working-directory: ./client
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLS_INTERACTIVE_SETUP_ENABLE: 1
