name: "PR check with testing"

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Package Setup
        run: yarn
        working-directory: ./client

      - name: Test
        run: yarn test
        working-directory: ./client
